# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceID', models.CharField(max_length=200)),
                ('TimeStamp', models.DateTimeField()),
                ('cellID', models.CharField(max_length=10)),
                ('LAC', models.CharField(max_length=10)),
                ('dBm', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceID', models.CharField(max_length=200)),
                ('TimeStamp', models.DateTimeField()),
                ('Lat', models.FloatField(null=True)),
                ('Long', models.FloatField(null=True)),
            ],
        ),
    ]
